repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        language: system
        entry: gofmt -w
        types: [go]

      - id: go-vet
        name: go vet
        language: system
        entry: env GOOS=linux go vet ./...
        pass_filenames: false
        types: [go]

      - id: go-build
        name: go build
        language: system
        entry: env GOOS=linux go build -o /tmp ./app/...
        pass_filenames: false
        types: [go]

      - id: go-test
        name: go test
        language: system
        entry: env GOOS=linux go test -timeout 10s ./app/...
        pass_filenames: false
        types: [go]
